build:
  version:"1.0"

accounts:
  message: "Welcome to cards related local APIS"
  contactDetails:
    name: "Loc Pham QA Leads"
    email: "phamxuanloc97@outlook.com"
  onCallSupport:
    - 0932-445-662
    - 84932-445-662